services:
  whoami:
    image: containous/whoami
    networks:
      - frontproxynet
    container_name: whoami
    labels:
      - "traefik.enable=true"
      # Service
      - "traefik.http.services.whoami.loadbalancer.server.scheme=http"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      # Router
      - "traefik.http.routers.whoami.rule=Host(${HOSTNAME})"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"

networks:
  frontproxynet:
    external: true
