global:
    scrape_interval: 15s

scrape_configs:
    - job_name: 'traefik'
      static_configs:
          - targets: ['traefik:8899']
    - job_name: 'host'
      static_configs:
#          - targets: ['host.docker.internal:9323', 'cadvisor:8080', 'node_exporter:9100']
          - targets: ['host.docker.internal:9323', 'node_exporter:9100']
