[log]
  level = "ERROR"

# https://doc.traefik.io/traefik/operations/ping/
[ping]

# https://doc.traefik.io/traefik/observability/metrics/prometheus/#entrypoint
[metrics]
  [metrics.prometheus]
    addServicesLabels = true
    addEntryPointsLabels = true
    addRoutersLabels = true
    entryPoint = "metrics"

# Limiting the Logs to Specific Fields
[accessLog]
  filePath = "/access.log"

  [accessLog.filters]
    statusCodes = ["400-403", "300-302", "500-503"]
    minDuration = "700ms"

[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.metrics]
    address = ":8899"

  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "web_secure"
      scheme = "https"
    [entryPoints.web.forwardedHeaders]
      insecure = true
      # Add here any additional reverse-proxy IPs (such as Cloudflare)
      trustedIPs = ["127.0.0.1", "192.168.0.1"]

  [entryPoints.web_secure]
    address = ":443"
    asDefault = true
    [entryPoints.web_secure.http]
      tls = true
    [entryPoints.web_secure.http3]
    [entryPoints.web_secure.forwardedHeaders]
      insecure = true
      # Add here any additional reverse-proxy IPs (such as Cloudflare)
      trustedIPs = ["127.0.0.1", "192.168.0.1"]

[api]
  dashboard = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false
  network = "frontproxynet"

[certificatesResolvers.letsencrypt.acme]
  email = "xxxx@xxxx.com"
  storage = "acme.json"
  # Use staging server during tests
  #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"
