apiVersion: 1

datasources:
    - name: prometheus
      type: prometheus
      # Keep this UID to make it the default datasource in alerting and dashboards.
      uid: default_prometheus_uid
      url: http://prometheus:9090
      isDefault: true
      basicAuth: false
      editable: false
